# Generated by Django 4.1.5 on 2023-02-01 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('colors_id', models.AutoField(primary_key=True, serialize=False)),
                ('colors_hex', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('items_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_name', models.CharField(max_length=256)),
                ('items_code', models.CharField(blank=True, max_length=100)),
                ('items_desc', models.TextField(blank=True)),
                ('items_buy_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('items_sale_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_Types',
            fields=[
                ('unit_types_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_types_name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items_Has_Colors',
            fields=[
                ('items_has_colors_id', models.AutoField(primary_key=True, serialize=False)),
                ('colors_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.colors')),
                ('items_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.items')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unit_types'),
        ),
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('inventories_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventories_available', models.IntegerField()),
                ('inventories_input', models.IntegerField(blank=True, null=True)),
                ('inventories_output', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.items')),
            ],
        ),
    ]
