# Generated by Django 4.1.5 on 2023-02-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_items_unit_type_inventories_unit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='users_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
