# Generated by Django 4.1.5 on 2023-02-13 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_users_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='user_id',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='app.users'),
            preserve_default=False,
        ),
    ]
